### ISSUE TITLE
Advanced code editor

### ISSUE THREAD

**Issue by honix** [honix/Pyno#10]
Would it be possible for the code editor to have line numbering to make it easier to find errors in the code?
_Originally posted by @GurePortela in https://github.com/honix/Pyno/issues/9#issuecomment-436701335_

Code highlighting of keywords.

**Comment by GurePortela** [comment]
number line in editor code,is possible?

**Comment by honix** [comment]
Yes, i think. It will be done, along with another editor features.

But this is not high priority task for me, i need to done some other work.

I will put "help wanted" tag here, meaning this issue can be done by any of contributors.

**Comment by drtrigon** [comment]
By the way we should support more standard key combinations like Ctrl+X, Ctrl-Z, etc.

**Comment by bilderbuchi** [comment]
maybe pull in some editor component of a UI package (qtpy, pysimplegui, whatever..) that offers this already (instead of coding it yourself), and embed the node graph in that GUI?

**Comment by honix** [comment]
@bilderbuchi pyglet (we using it now) have pretty good text rendering features. I think, it is not so hard to add number line or key word highlighting, and autocomplete some day later.

**Comment by drtrigon** [comment]
Ctrl+C, Ctrl+V should also work with other programs (currently it only works within Pyno).

**Comment by drtrigon** [comment]
I don't see how to add syntax highlighting easily - I leave this for someone else... ;)

**Comment by drtrigon** [comment]
> Code highlighting of keywords.

Also done in #17
