### ISSUE TITLE
Save python script from pyno-file

### ISSUE THREAD

**Issue by drtrigon** [honix/Pyno#14]
This was just an idea - but can we maybe use the processor to merge and output the python code (instead of executing) and by that support saving to python script? That would allow to export complex code into a python script and import it into a compact (and may be faster) single node again. Would also allow to re-use code in other programs etc.

**Comment by honix** [comment]
I see approach when pyno engine becomes separatly from GUI, to will allow run patches without GUI.

I think its not important thing to do now, but i like the idea.

**Comment by drtrigon** [comment]
https://github.com/honix/Pyno/issues/18 will put the nodes code already in a separate python scripts. Then the thing left is to glue these snippets together.

> pyno engine becomes separatly from GUI

Sounds great.

> I think its not important thing to do now, but i like the idea.

I agree. Actually this issue should be solved as by-product from other improvements to Pyno (like separate engine, #18, etc.). So maybe this is a guideline or milestone for future developments.
