### ISSUE TITLE
Add 'cleanup' binding

### ISSUE THREAD

**Issue by honix** [honix/Pyno#24]
Everything in node's code executed once, in "read time".

If there was 'call' binding, this 'call' function will be called as main node process - "run time".

I'm considering to add 'cleanup' binding which will be called on node deletion or restart. For example close opened graphical window.

Maybe there is more userfull bindings (callbacks) to add..

**Comment by drtrigon** [comment]
Close files. Important for hardware like `/dev/ttyUSB` etc.

**Comment by honix** [comment]
Done in 4497be3.

Example usege in examples/particles.pn and examples/ping-pong.pn

**Comment by honix** [comment]
Done in 4497be3.

Example usage in examples/particles.pn and examples/ping-pong.pn
