### ISSUE TITLE
Simpler node definition using decorators

### ISSUE THREAD

**Issue by bilderbuchi** [honix/Pyno#25]
[Right now](https://github.com/honix/Pyno/issues/7#issuecomment-436401718), the pattern to define the code of a node is, if I understand correctly:
```
def helper(a, b):
  return a + b

def add(a=0, b=0):
  result = helper(a, b)
  return result

call = add
```
or
```
import calendar
call = calendar.isleap
```
It would be nice if this additional assignment to the arbitrarily named `call` object could be hidden from the user. I am thinking that it should be possible using python decorators to register the wanted callable with the node it belongs to, e.g. like this:
```
@node_target
def helper(a, b):
  return a + b

def add(a=0, b=0):
  result = helper(a, b)
  return result
```
or
```
import calendar
node_target(calendar.isleap)
```
Note how it's possible to pick out which callable you want assigned from several candidates, and how you don't rely on having a specifically-named callback object that just hangs around in that scope. It would also maybe be easier to handle when creating many nodes from another module.
Does this sound attractive?

**Comment by honix** [comment]
Interesting. But i think binding is much more easier concept for beginers than decorators.

By the time we want to introduce more "keywords". My opinion that it will fit well with current concept.

Again binding becomes more hackable for user it is property i want stay. Hackability gives power to the user, in the ways we didnt expect.

**Comment by GurePortela** [comment]
The works made in previous versions are not being loaded by the new versions. It would be possible to compatibilize, and in the future you. think of making a small manual for non-programmers, and also a function bank, or a possible one for the Pyno program to run on other versions of scientific Python?
Congratulations, it's getting wonderful!

**Comment by GurePortela** [comment]
![snap 2018-11-16 at 05 43 24](https://user-images.githubusercontent.com/36675042/48610533-abe8e080-e963-11e8-8649-f9b18864c2e3.png)
![snap 2018-11-16 at 05 43 48](https://user-images.githubusercontent.com/36675042/48610535-ac817700-e963-11e8-80a4-fe01ddfc29e7.png)
Example below the same pyno file opened in the old version and the new version running in Python3.7

**Comment by honix** [comment]
@GurePortela yes, there was some rule breaks in saving format. We considering to make standalone script to port old saves to new version.

**Comment by honix** [comment]
@GurePortela try to convert your work using this script https://github.com/honix/Pyno/blob/master/utils/resave.py

**Comment by GurePortela** [comment]
Jóia
