### ISSUE TITLE
Create standard/installable package

### ISSUE THREAD

**Issue by bilderbuchi** [honix/Pyno#26]
Pyno should be turned into a package that you can install with `pip` and/or `conda`. This will also make maintenance (like definining dependencies etc) easier. 
It would also be sound practice to add tests (via pytest) and continuous integration (e.g. via travis-ci).

I already have an idea about the necessary steps (have created packages before), and can do that if desired.

**Comment by drtrigon** [comment]
I am ambiguous ... 

Unittest are very useful! I just don't see how you can test the GUI?

Install through pip are very useful! But the fact that pyno requirements are already easy to install and pyno too as it only needs to unpack less than 1MB from a archive is very valuable. If we do not need to change the sources, continue to try to keep the required packages on a minimum and still provide the source code (not only wheels) I do not see a reason against a pip package.

**Comment by bilderbuchi** [comment]
The point of forming a package is that it is *the* standard way to install python software/libraries/packages, so why be different.
GUI tests can be accomplished using a virtual framebuffer (xvfb), but you don't have to test it. If there is proper separation of concerns, one can test all the programs components separately.

**Comment by drtrigon** [comment]
> one can test all the programs components separately

... except the GUI. I do not agree here just because there is no way to test the GUI yet does not mean it is not necessary. The graphical editor should be tested as well. What about e.g. Squish: https://www.froglogic.com/blog/squish-python/ ?

**Comment by bilderbuchi** [comment]
I don't know what you mean with "no way" - e.g. for another way to test e.g. Qt applications see https://pypi.org/project/pytest-qt/, I'm sure there are others for other GUI layers. Never personally seen/used swish before.

**Comment by drtrigon** [comment]
The "Interactive tests, default type" seem to be a starting point.
