### ISSUE TITLE
Add PYNO_HOME variable into user scope

### ISSUE THREAD

**Issue by honix** [honix/Pyno#29]
PYNO_HOME will point to the Pyno folder with examples, nodes and etc., so user can target them regardless initial working directory.

**Comment by bilderbuchi** [comment]
Nodes can be referenced as normal in python - pyno.nodes.somenode

**Comment by bilderbuchi** [comment]
Also, best use the pkg_resources API for this, in case you're dealing with a zipped install or somesuch - there is an accessory function for whole directories in there.

**Comment by honix** [comment]
Archived
