### ISSUE TITLE
Enhance install instructions

### ISSUE THREAD

**Issue by drtrigon** [honix/Pyno#30]
The instructions given in https://github.com/honix/Pyno#how-to-run are confusing (very brief). Am I right that they mean something like:

> $ git clone https://github.com/honix/Pyno.git
$ cd Pyno
$ pip install .

... and the instructions given in https://github.com/honix/Pyno#how-to-modify in that case:

> $ git clone https://github.com/honix/Pyno.git
$ cd Pyno
$ pip install -e .

I like the approach using a clone with `pip install .` I wonder what happens if I omit the pip install and just do a clone?

The README should be enhanced to include a bit more specific step-by-step install instructions.

**Comment by honix** [comment]
There is actually oneliner install:
```
pip install git+https://github.com/honix/Pyno.git
```

**Comment by bilderbuchi** [comment]
> The instructions given in https://github.com/honix/Pyno#how-to-run are confusing (very brief).

sorry about that, I wrote it in a hurry yesterday.

> that they mean something like

yes, correct on both counts.

> what happens if I omit the pip install and just do a clone?

then you lose the ability to just do, in any directory (e.g. where your pn files are in some art project folder), `pyno` in your terminal to start the application. Instead, you have to start it from within Python (this pyno "entry point" I created is the pythonic way to create an "executable" part of an installed library).

In the future (when Pyno is on PyPI) it will even be easier:
```
pip install Pyno
pyno
```

> more specific step-by-step 
I'm not sure how to be more specific, as these already are all the steps you need to do. If I have forgotten anything, feel free to enhance! :-)

**Comment by drtrigon** [comment]
See #31.

**Comment by drtrigon** [comment]
I do not understand the changes made to my pull request, please see #31.
