### ISSUE TITLE
Add Continuos Integration

### ISSUE THREAD

**Issue by bilderbuchi** [honix/Pyno#36]
Now that it's possible to run pytest on the code, it would be wise to add a Continuos Integration service, which will run tests on all commits and PRs to minimise the amount of breakage introduced. This will also hopefully incentivise writing of further tests for the codebase.
I would recommend Travis (www.travis-ci.com) as you can just register with your github credentials, and it's free for open source projects. If not familiar with how this works for a Python project, see https://docs.travis-ci.com/user/languages/python.

**Comment by drtrigon** [comment]
You can also got the next step and create a docker.

**Comment by bilderbuchi** [comment]
yeah but why?

**Comment by honix** [comment]
Done

**Comment by bilderbuchi** [comment]
:+1:

**Comment by GurePortela** [comment]
[image: image.png]
accumulator I do not know how this is working

Em qua, 21 de nov de 2018 às 07:41, Christoph Buchner <
notifications@github.com> escreveu:

**Comment by drtrigon** [comment]
Do we have a docker now? No docker no further development (from my side)...

**Comment by honix** [comment]
@drtrigon sorry, i don't know any thing about docker! Why docker is important for you?

**Comment by drtrigon** [comment]
When we do CI, pip, unittest, etc. we should be consequent and also add a docker image. Especially when these things lead to issues as seen. I just dont have time and motivation to figure out how and what to setup whenever such changes appear. A docker image would provide a standard way of setting up for development and usage (install docker and do a pull). It needs to contain a git clone from the pyno repo such that development, committing and running for testing is easily possible - no worrying about python versions, pip usage, config, setup, etc.
