### ISSUE TITLE
entrance and exit

### ISSUE THREAD

**Issue by GurePortela** [honix/Pyno#45]
Hello !
It would be possible that the node would be freer to make the 
connections of the input and output pins as in the nodes made in 
the Flow-Based Programming (FBP) by J Paul Morrison ?
this would make it easier to improve the layout of the project.

Olá !
Seria possível que o nó fosse mais livre para fazer o
conexões dos pinos de entrada e saída como nos nós feitos em
a programação baseada em fluxo (FBP) por J Paul Morrison?
Isso tornaria mais fácil melhorar o layout do projeto.

**Comment by honix** [comment]
Hello!

This is a good thing to try, but unfortunately I cant find time for Pyno project.

It is open for contributions, but main development is frozen.
