### ISSUE TITLE
File format as json + OrderedDict?

### ISSUE THREAD

**Issue by bilderbuchi** [honix/Pyno#9]
Seeing some of the huge diffs of .pn files for small changes, and seeing the structure of the contents, I am wondering if it would be worthwhile to make the file format json instead (I think it's already quite near?), and store it in a prettyfied/line-broken form. 
If you [couple it with OrderedDict](https://stackoverflow.com/a/6921760/599884), this should preserve insertion order and minimise the diffs between saves. 
YAML would of course also be an option.

**Comment by honix** [comment]
Yep! This is thing todo.

**Comment by GurePortela** [comment]
Just one more thing.
Would it be possible for the code editor to have line numbering to make it easier to find errors in the code?

**Comment by drtrigon** [comment]
Implemented and immediately got an new issue as json is not able to support tuples, see https://stackoverflow.com/questions/15721363/preserve-python-tuples-with-json - the fix is in the pull request too.

Is any better and more general format for python out there?

**Comment by drtrigon** [comment]
Can be closed due to https://github.com/honix/Pyno/pull/11

**Comment by honix** [comment]
Node's code need to use newline break.

**Comment by drtrigon** [comment]
I don't get this - what is the problem? I did not notice an issue...

**Comment by honix** [comment]
@drtrigon nodes's code saved in one big line now without breaking, git will commit whole code if change.

But #18 will fix it later.

**Comment by honix** [comment]
Breaking serialized code into lines done at 3a25b19
